In [1]:
#numpy常用函数
#定义数据类型
import numpy as np
dt = np.dtype('i4')#‘i4’相当于int32
print (dt)
print (type(dt))

int32
<class 'numpy.dtype'>


In [12]:
students = np.dtype([("name",'S10'),("age",'int32'),("marks",'f4')])
print(students)
print(type(students))

[('name', 'S10'), ('age', '<i4'), ('marks', '<f4')]
<class 'numpy.dtype'>


In [13]:
#多维数组
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr = np.array([1,2,3,8,6,7,4],ndmin=3)
arr

array([[[1, 2, 3, 8, 6, 7, 4]]])

In [18]:
arr = np.array([1,4,5,6],dtype='f')
arr

array([1., 4., 5., 6.], dtype=float32)

In [3]:
import numpy as np
arr = np.empty([3,2],dtype='f')
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [5]:
#结构化数据类型
student = np.dtype([("name",'S10'),("age",'int32'),("marks",'f4')])
arr = np.array([("zxh",20,98.4),("armanda",20,99.2)],dtype = student)
arr

array([(b'zxh', 20, 98.4), (b'armanda', 20, 99.2)],
      dtype=[('name', 'S10'), ('age', '<i4'), ('marks', '<f4')])

In [7]:
arr = np.full([3,2],fill_value=525,dtype='i4')
arr

array([[525, 525],
       [525, 525],
       [525, 525]])

In [8]:
#单位矩阵
arr = np.eye(10,dtype='i4')
arr

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [9]:
#arange函数——>较为重要
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [12]:
s=b"zxh" #记得加b
arr=np.frombuffer(s,dtype='S1',offset=2)
arr

array([b'h'], dtype='|S1')

In [18]:
#可迭代
x=[1,2,3]
z=iter(x)
print(z)
arr=np.fromiter(z,dtype='i4')
arr

array([1, 2, 3])

In [19]:
#等差数列 开始值、终止值、个数
arr=np.linspace(1,10,3,dtype='f')
arr

array([ 1. ,  5.5, 10. ], dtype=float32)

In [21]:
#等比数列 开始值、终止值、个数
#base是对数的底数
arr=np.logspace(1,10,2,dtype='f')
arr

array([1.e+01, 1.e+10], dtype=float32)

In [2]:
#生成随机数(可数字、可多维数组)
import numpy as np
arr=np.random.rand(2)
arr

array([0.09328369, 0.96646219])

In [6]:
arr=np.random.rand(3,5)#二维数组
arr

array([[0.78973819, 0.57973206, 0.73928736, 0.7526231 , 0.87615638],
       [0.05882278, 0.49331885, 0.13395625, 0.40645179, 0.99943135],
       [0.98354999, 0.16259352, 0.51234182, 0.77467681, 0.12321945]])

In [7]:
arr=np.random.rand(3,2,4)#三维数组
arr

array([[[0.29772562, 0.02194397, 0.19553039, 0.20367237],
        [0.02154778, 0.90046556, 0.37680667, 0.19597566]],

       [[0.40564053, 0.53009725, 0.35213868, 0.25871106],
        [0.69066694, 0.78778231, 0.61891318, 0.97020936]],

       [[0.23750213, 0.92951917, 0.20005099, 0.9607063 ],
        [0.08394611, 0.55699253, 0.43584866, 0.59392641]]])

In [10]:
arr=np.random.random(4)#不可生成多维数组
arr

array([0.55019993, 0.92363897, 0.25353105, 0.54814461])

In [16]:
arr=np.random.randint(0,10,5)#下限（包含）、上限（不包含）、个数、类型
arr

array([6, 2, 6, 2, 9])

In [20]:
#返回的样本具有标准正态分布——N（0，1）
arr=np.random.randn(4,5,4)
arr

array([[[-0.08265446,  0.51075658,  1.25090321,  0.29554415],
        [-2.04190363, -1.46908424, -1.74440716, -1.48439571],
        [-1.01724349,  0.55769199,  0.21295437, -0.32309833],
        [-1.4085315 , -0.52128729,  2.94135968, -0.08711449],
        [-1.54618537,  2.45366089, -1.13622163,  1.11883019]],

       [[-0.59202796, -2.01856586, -0.67674057, -0.65728603],
        [ 1.01673225,  0.27035016,  1.14690978,  1.66668192],
        [-0.62683879,  0.87453342, -1.28365935,  0.89441044],
        [-0.46660024, -1.56074024,  0.82344488, -0.4698484 ],
        [ 0.00870723, -0.29722801, -0.55603241,  1.42829686]],

       [[-1.37521604, -0.95031417,  0.02837865,  0.59870577],
        [ 0.6152847 ,  1.74770684, -0.3945024 ,  1.66853058],
        [ 1.33618312, -1.15990289, -2.42915025, -1.40634918],
        [-1.15478228,  1.08427775,  0.02852721, -0.23546105],
        [ 1.28357423,  1.68672035, -1.93618267,  0.23276897]],

       [[ 0.56497209,  1.56230572, -0.40441677, -1.15537304],
  

In [ ]:
#高斯分布的概率密度随机数,分布中心、标准差、元素的个数
import numpy as np
arr=np.random.normal(loc=1,scale=2,size=5)
arr

In [ ]:
#对比python中的列表，numpy的速度快很多
import random
list=[]
for i in range(10000000000):
    list.append(random.random())
import time
t1=time.time()
ret=sum(list)
t2=time.time()
print("耗时":(t2-t1))

In [5]:
import numpy as np
arr=np.arange(40)
print(arr)
print(arr.ndim)
print("\n")
arr2=arr.reshape(2,5,4)
print(arr2)
print(arr2.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
1


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]]
3


In [12]:
arr=np.array([[1,4,5],[9,4,3]])
arr.shape=(3,2)#调整格式
print(arr)
print(arr.shape)
arr=arr.reshape(1,2,3)
arr

[[1 4]
 [5 9]
 [4 3]]
(3, 2)


array([[[1, 4, 5],
        [9, 4, 3]]])

In [26]:
import numpy as np
arr=np.arange(10)
print(arr)
arr[3]
s=slice(1,6,2) #切片:start,stop,step
print(arr[s])
print("\n")
arr2=arr[1:6:2]
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5]


[1 3 5]


In [22]:
import numpy as np
arr=np.arange(10)
print(arr)
print(arr[2:])
arr1=arr[2:]
print(arr1)
arr2=arr[2:8]
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 3 4 5 6 7]


In [31]:
arr=np.arange(15)
arr.shape=(3,5)
print(arr)
print("\n")
arr1=arr[2][3]
print(arr1,type(arr1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


13 <class 'numpy.int32'>


In [38]:
arr=np.arange(15)
arr.shape=(3,5)
print(arr)
print("\n")
arr1=arr[2,3]
print(arr1,type(arr1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


13 <class 'numpy.int32'>


In [33]:
arr=np.arange(15)
arr.shape=(3,5)
print(arr)
print("\n")
arr1=arr[...,3]
print(arr1,type(arr1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


[ 3  8 13] <class 'numpy.ndarray'>


In [37]:
#整数数组索引（获取（0,0），（1,1），（2,0）位置的元素）
import numpy as np
arr=np.array([[1,2,3],[4,6,7],[9,5,6]])#数组里的维度[[]]
print(arr[[0,1,2],[0,1,0]])#行、列

[1 6 9]


In [55]:
arr=np.arange(9)
arr=arr.reshape(3,3)
print(arr)
print("\n")
rows=np.array([[0,0],[2,2]])
cols=np.array([[0,2],[0,2]])
arr3=arr[rows,cols]
print(arr3)#四角的元素值
print("\n")
print(arr[1:3,1:3])
print("\n")
print(arr[arr>2])

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[[0 2]
 [6 8]]


[[4 5]
 [7 8]]


[3 4 5 6 7 8]


In [56]:
arr=np.array([np.nan,1,2,3,np.nan,8,3,2])
print(arr)
print(arr[np.isnan(arr)])#输出nan
print(arr[~np.isnan(arr)])#除了nan以外的

[nan  1.  2.  3. nan  8.  3.  2.]
[nan nan]
[1. 2. 3. 8. 3. 2.]


In [1]:
import os
print(os.path.abspath('.'))

C:\Users\张笑菡
